name: Run web scraper

on: 
  schedule:
    - cron: '30 5 * * *' # Run the workflow every day at 5:30 UTC
#on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute price scrape for SE1
        run: python swedish_contracts_se1_linux.py

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit changes
        run: |
          git pull origin main --rebase  # Ensure the local copy is up-to-date with remote
          git add swedish_contracts/*.csv
          git commit -m "Add new scraped data CSV files"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required to authenticate the commit
          
      - name: Execute price scrape for SE2
        run: python swedish_contracts_se2_linux.py

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit changes
        run: |
          git pull origin main --rebase  # Ensure the local copy is up-to-date with remote
          git add swedish_contracts/*.csv
          git commit -m "Add new scraped data CSV files"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required to authenticate the commit
          
      - name: Execute price scrape for SE3
        run: python swedish_contracts_se3_linux.py

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit changes
        run: |
          git pull origin main --rebase  # Ensure the local copy is up-to-date with remote
          git add swedish_contracts/*.csv
          git commit -m "Add new scraped data CSV files"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required to authenticate the commit

      - name: Execute price scrape for SE4
        run: python swedish_contracts_se4_linux.py

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit changes
        run: |
          git pull origin main --rebase  # Ensure the local copy is up-to-date with remote
          git add swedish_contracts/*.csv
          git commit -m "Add new scraped data CSV files"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required to authenticate the commit
